name: Publish Docker Image
description: >
  Log in to a container registry and build + push a Docker image.

inputs:
  registry:
    description: Container registry hostname
    required: false
    default: ghcr.io
  username:
    description: Registry login username
    required: true
  password:
    description: Registry login password or token
    required: true
  context:
    description: Docker build context path (relative to repo root)
    required: true
  tags:
    description: Fully-qualified image tag(s), newline-separated if multiple
    required: true
  push:
    description: Whether to push the image after building
    required: false
    default: 'true'

outputs:
  digest:
    description: Image digest produced by docker/build-push-action
    value: ${{ steps.build-push.outputs.digest }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - id: build-push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
